# Generated by Django 2.2.13 on 2021-03-28 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='label_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labels',
            name='label_shortcut',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('portrait', models.ImageField(max_length=255, upload_to='portraits')),
                ('labels', models.ManyToManyField(to='user.Labels')),
                ('upload_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Upload_text')),
            ],
        ),
    ]
