# Generated by Django 2.2.13 on 2021-03-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210328_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='label_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='labels',
            old_name='label_shortcut',
            new_name='shortcut',
        ),
        migrations.RenameField(
            model_name='labels',
            old_name='label_name',
            new_name='value',
        ),
    ]
