# Generated by Django 2.2.13 on 2021-03-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210329_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='upload_text',
        ),
        migrations.AddField(
            model_name='labels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Userdata'),
        ),
        migrations.AddField(
            model_name='upload_text',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Userdata'),
        ),
    ]
