# Generated by Django 3.1.7 on 2021-03-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210329_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='portrait',
        ),
        migrations.AddField(
            model_name='userdata',
            name='avatar',
            field=models.ImageField(default='', max_length=255, upload_to='avatar'),
            preserve_default=False,
        ),
    ]
