# Generated by Django 3.1.7 on 2021-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=30)),
                ('medicine', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('tool', models.CharField(max_length=30)),
            ],
        ),
    ]
